#!/usr/bin/env python3
"""Turn the mascot masters into what the app ships, and write the manifest.

The masters in `Mascots/<Species>/` are 1024-1536 px PNGs with a transparent
background — there is nothing to cut out, so this only trims each one to the
character's own bounding box, scales it down and quantises it. Trimming matters
as much as scaling: the art sits in a big empty frame, and without it every
picture in the app would be a small character floating in whitespace.

Also writes `www/mascots.js`, the list of which pictures actually exist. The app
reads it to decide when to fall back to the drawn figure, which is what lets an
incomplete mascot ship without a broken slot anywhere.

    python3 tools/build-mascots.py
"""
import glob
import json
import os
import sys

from PIL import Image

SRC = {"rabbit": "Mascots/Rabbit", "fox": "Mascots/Fox", "bear": "Mascots/Bear"}
OUT = "www/img"
MANIFEST = "www/mascots.js"

MAX = 720        # long side; ~48 KB a picture, and still sharp on the workout screen
COLORS = 220     # 8-bit palette keeps the alpha and cuts the file to a fifth

# every picture the app knows how to use, in the order the manifest lists them
POSES = ["zvezdice", "macka", "psic", "leptiric", "pretklon", "kobra", "mostic",
         "spaga", "arabeska", "linija", "prsti", "sveca", "daska", "noge", "cuk",
         "lastavica", "cucanj", "iskorak", "dete"]
STATES = ["sit", "happy", "hero", "spava", "portret"]


def build(species, folder):
    made, sizes = [], 0
    for name in POSES + STATES:
        path = os.path.join(folder, "%s-%s.png" % (species, name))
        if not os.path.exists(path):
            continue
        im = Image.open(path).convert("RGBA")
        box = im.getbbox()
        if box:
            im = im.crop(box)
        im.thumbnail((MAX, MAX), Image.LANCZOS)
        dst = os.path.join(OUT, "%s-%s.png" % (species, name))
        im.quantize(colors=COLORS, method=Image.FASTOCTREE).save(dst, optimize=True)
        made.append(name)
        sizes += os.path.getsize(dst)
    return made, sizes


def main():
    missing = [f for f in SRC.values() if not os.path.isdir(f)]
    if missing:
        sys.exit("missing folders: " + ", ".join(missing))
    os.makedirs(OUT, exist_ok=True)

    manifest = {}
    for species, folder in SRC.items():
        made, sizes = build(species, folder)
        manifest[species] = made
        gaps = [p for p in POSES if p not in made] + [s for s in STATES if s not in made]
        print("%-7s %2d pictures  %5.0f KB%s" %
              (species, len(made), sizes / 1024,
               "   still missing: " + ", ".join(gaps) if gaps else ""))

    with open(MANIFEST, "w") as f:
        f.write("/* Generated by tools/build-mascots.py — which mascot pictures\n"
                "   exist. Anything not listed falls back to the drawn figure. */\n")
        f.write("var MASCOT_ART = %s;\n" % json.dumps(manifest, indent=2, sort_keys=True))
    print("wrote " + MANIFEST)

    stale = [p for p in glob.glob(os.path.join(OUT, "lili-*.png"))]
    if stale:
        print("\nleft alone, no longer referenced once the swap lands:")
        for p in sorted(stale):
            print("  " + p)


if __name__ == "__main__":
    main()
